// Cache for channel logos found/generated by the edge function
const LOGO_CACHE_KEY = 'mi-player-logo-cache';
const LOGO_PENDING_KEY = 'mi-player-logo-pending';
const CACHE_EXPIRY_MS = 7 * 24 * 60 * 60 * 1000; // 7 days

interface LogoCacheEntry {
  url: string | null;
  timestamp: number;
}

type LogoCache = Record<string, LogoCacheEntry>;

const getCache = (): LogoCache => {
  try {
    const raw = localStorage.getItem(LOGO_CACHE_KEY);
    return raw ? JSON.parse(raw) : {};
  } catch {
    return {};
  }
};

const saveCache = (cache: LogoCache): void => {
  try {
    localStorage.setItem(LOGO_CACHE_KEY, JSON.stringify(cache));
  } catch {
    // Storage full - clear old entries
    const entries = Object.entries(cache);
    entries.sort((a, b) => a[1].timestamp - b[1].timestamp);
    const trimmed = Object.fromEntries(entries.slice(entries.length / 2));
    try {
      localStorage.setItem(LOGO_CACHE_KEY, JSON.stringify(trimmed));
    } catch { /* ignore */ }
  }
};

// Get cached logo URL for a channel
export const getCachedLogo = (channelName: string): string | null | undefined => {
  const cache = getCache();
  const entry = cache[channelName];
  if (!entry) return undefined; // Not cached
  if (Date.now() - entry.timestamp > CACHE_EXPIRY_MS) {
    // Expired
    delete cache[channelName];
    saveCache(cache);
    return undefined;
  }
  return entry.url; // null means "no logo found", string means found
};

// Save a logo URL (or null if not found) to cache
export const setCachedLogo = (channelName: string, url: string | null): void => {
  const cache = getCache();
  cache[channelName] = { url, timestamp: Date.now() };
  saveCache(cache);
};

// Batch save logos
export const setCachedLogos = (logos: Record<string, string | null>): void => {
  const cache = getCache();
  const now = Date.now();
  for (const [name, url] of Object.entries(logos)) {
    cache[name] = { url, timestamp: now };
  }
  saveCache(cache);
};

// Track which channels are currently being fetched to avoid duplicate requests
const pendingChannels = new Set<string>();

export const isPending = (channelName: string): boolean => pendingChannels.has(channelName);
export const markPending = (channelName: string): void => { pendingChannels.add(channelName); };
export const clearPending = (channelName: string): void => { pendingChannels.delete(channelName); };
export const clearAllPending = (): void => { pendingChannels.clear(); };
